name: Docker Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: docker/compose-action@v3

    - name: Build and Start Services
      run: docker compose up -d --build

    - name: Wait for Application
      run: |
        echo "Waiting for the application to be ready..."
        sleep 10

    - name: Test Application
      run: |
        curl -f http://localhost:3000 || exit 1
