name: Docker Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Services
      run: |
        docker-compose up -d --build

    - name: Wait for Application
      run: |
        echo "Waiting for the application to be ready..."
        sleep 10

    - name: Test Application
      run: |
        curl -v http://localhost:3000 || exit 1

    - name: Stop Services
      run: |
        docker-compose down
