name: Docker Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        # Install Docker CLI
        sudo apt-get update
        sudo apt-get install -y docker.io
        # Docker Compose V2 is included with the Docker CLI now, so no need to install separately

    - name: Verify Docker and Compose installation
      run: |
        docker --version
        docker compose --version  # Note: Use `docker compose` instead of `docker-compose`

    - name: Build and Start Services
      run: docker compose up -d --build  # Use `docker compose` instead of `docker-compose`

    - name: Wait for Application
      run: |
        echo "Waiting for the application to be ready..."
        sleep 10

    - name: Test Application
      run: |
        curl -v http://localhost:3000 || exit 1
