name: Docker Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        # Update apt package index and install Docker dependencies
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
          
        # Add Docker's official GPG key and Docker repository
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc > /dev/null
        echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Install Docker and Docker Compose
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        # Install Docker Compose (v2)
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker and Compose installation
      run: |
        docker --version
        docker-compose --version

    - name: Build and Start Services
      run: docker-compose up -d --build

    - name: Wait for Application
      run: |
        echo "Waiting for the application to be ready..."
        sleep 10

    - name: Test Application
      run: |
        curl -v http://localhost:3000 || exit 1
